
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_C = 13;
  public static final int COMA = 11;
  public static final int HORARIO = 3;
  public static final int COLON = 10;
  public static final int NUMBER = 14;
  public static final int USER = 9;
  public static final int OPEN_C = 12;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int SALON = 5;
  public static final int CURSO = 4;
  public static final int EDIFICIO = 6;
  public static final int ESTUDIANTE = 8;
  public static final int CATEDRATICO = 7;
  public static final int error = 1;
  public static final int ASIGNAR = 2;
  public static final int WORD = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASIGNAR",
  "HORARIO",
  "CURSO",
  "SALON",
  "EDIFICIO",
  "CATEDRATICO",
  "ESTUDIANTE",
  "USER",
  "COLON",
  "COMA",
  "OPEN_C",
  "CLOSE_C",
  "NUMBER",
  "STRING",
  "WORD"
  };
}

