/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Estudiante;

import Estructuras.ListaSimple;
import Excepciones.ScheduleNotFound;
import Excepciones.StudentNotFound;
import GUI.Login;
import Modelos.Asignacion;
import Modelos.Curso;
import Modelos.Estudiante;
import Modelos.Horario;
import Nodos.NodoSimple;
import java.text.SimpleDateFormat;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anclenius
 */
public class Main_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Main_Estudiante
     */
    private Estudiante estudiantea;
    private static SimpleDateFormat format = new SimpleDateFormat("hh:mm");
    public Main_Estudiante(long carnet) {
        initComponents();
        this.setVisible(true);
        estudiantea = Controlador.Estructuras.estudiantes.buscar(carnet);
        jTextField1.setText(carnet+"");
        jTextField2.setText(estudiantea.getNombre());
        fillTable(estudiantea);
        
    }
    
    public Main_Estudiante(Estudiante estudiante) {
        initComponents();
        this.setVisible(true);
        jTextField1.setText(estudiante.getId()+"");
        jTextField2.setText(estudiante.getNombre());
        fillTable(estudiante);
        
    }
    
    public void fillTable(Estudiante estudiante) {
        ListaSimple lista = estudiante.getAsignaciones();
        NodoSimple aux = lista.inicio;
        while(aux != null) {
            addDatatoJTable((Asignacion)aux.getInfo());
            aux = aux.getSiguiente();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estudiante");

        jLabel1.setText("Carnet");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        jLabel2.setText("Nombre");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Creditos", "Semestre", "Zona", "Final", "Nota Final"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Lista de Cursos Asignados");

        jButton1.setText("Asignar Curso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            asignarCurso();
            eliminar();
            fillTable(estudiantea);
        } catch (Exception ex) {
            System.out.println("Error sin precedencia");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
    
    public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
    }
    
    public void addDatatoJTable(Asignacion asignacion){
        Horario horario = asignacion.getHorario();
        Curso curso = horario.getCurso();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[7];
            rowData[0] = curso.getCodigo();
            rowData[1] = curso.getNombre();
            rowData[2] = curso.getCreditos();
            rowData[3] = curso.getSemestre();
            rowData[4] = asignacion.getZona();
            rowData[5] = asignacion.getFinal();
            rowData[6] = asignacion.getFinal() + asignacion.getZona();
            model.addRow(rowData);
    }
    
    public void asignarCurso(){
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        JLabel label = new JLabel("Seleccione un curso");
        JComboBox combo = new JComboBox<>();
        JLabel l1 = new JLabel("Zona");
        JTextField f1 = new JTextField();
        f1.setColumns(10);
        JLabel l2 = new JLabel("Final");
        JTextField f2 = new JTextField();
        f1.setColumns(10);
        ListaSimple lista = Controlador.Estructuras.horarios.getHorarios();
        NodoSimple aux = lista.inicio;
        Horario horario;
        while(aux != null) {
            horario = (Horario)aux.getInfo();
            combo.addItem(horario.getCodigo()+". "+horario.getCurso().getNombre()+" Hora: " + format.format(horario.getHoraInicial()) + " - " + format.format(horario.getHoraFinal()));
            aux = aux.getSiguiente();
        }
        panel.add(label);
        panel.add(combo);
        panel.add(l1);
        panel.add(f1);
        panel.add(l2);
        panel.add(f2);
        String[] options = new String[]{"Cancelar", "Aceptar"};
        int option = JOptionPane.showOptionDialog(null, panel, "Seleccionar horario",
                        JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                        null, options, options[1]);
        if(option == 1) // pressing OK button
        {
            
            try {
                String a = (String) combo.getSelectedItem();
                String b = a.substring(0,a.indexOf("."));
                int no = Integer.parseInt(b);
                int n1 = Integer.parseInt(f1.getText());
                int n2 = Integer.parseInt(f2.getText());
                Controlador.Estructuras.asignarCurso(Long.parseLong(jTextField1.getText()), no, n1, n2);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Datos mal ingresados");
            } catch (ScheduleNotFound | StudentNotFound ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
